services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: rules_user
      POSTGRES_PASSWORD: rules_password
      POSTGRES_DB: rules_db
    ports:
      - "5432:5432"
    volumes:
      - rules_automation_postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://rules_user:rules_password@db:5432/rules_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api

volumes:
  rules_automation_postgres_data:
